import type { Locale } from "../interpretation/types";

/**
 * UI chrome translations (M4 — full vi/zh/en parity).
 *
 * AGENTS.md §3: no hardcoded display strings. Every user-facing label in the
 * components comes from here, keyed by `MessageKey`, resolved through the
 * LocaleProvider's `useT()`. This is UI chrome only — the *reading itself* is
 * generated by the model in the same locale (see lib/interpretation), and the
 * verified hexagram corpus text is never translated here (AGENTS.md §2).
 *
 * The reading/UI locale are one and the same: whatever the person selects in
 * the LanguageSwitcher drives both the chrome and the language of the reading.
 */
export interface Messages {
  // Landing
  "landing.subtitle": string;
  "landing.tagline1": string;
  "landing.tagline2": string;
  "landing.begin": string;
  "landing.beginHint": string;

  // Question entry
  "entry.placeholder": string;
  "entry.submit": string;
  "entry.suggest": string;
  "entry.thinking": string;

  // Casting ceremony
  "cast.first": string;
  /** Uses {n} for the line number being cast. */
  "cast.line": string;
  "cast.continue": string;

  // Reading
  "reading.yourQuestion": string;
  "reading.consulting": string;
  "reading.error.422": string;
  "reading.error.502": string;
  "reading.error.other": string;
  "reading.retry": string;
  "reading.askAnother": string;
  "reading.upperTrigram": string;
  "reading.lowerTrigram": string;
  "reading.image": string;
  "reading.cardJudgment": string;
  "reading.cardMeaning": string;
  "reading.cardAdvice": string;
  "reading.expand": string;
  "reading.collapse": string;
  "reading.advicePending": string;
  "reading.castAnother": string;
  "reading.home": string;

  // Clarification (folded into entry in T3; kept localized in the meantime)
  "clarify.placeholder": string;
  "clarify.askAsIs": string;
  "clarify.add": string;

  // Language switcher (the languages name themselves)
  "lang.vi": string;
  "lang.zh": string;
  "lang.en": string;

  // Navigation
  "nav.exit": string;
}

export type MessageKey = keyof Messages;

export const messages: Record<Locale, Messages> = {
  vi: {
    "landing.subtitle": "KINH DỊCH",
    "landing.tagline1": "Bộ kinh điển huyền bí phương Đông",
    "landing.tagline2": "64 Quẻ — Thiên Địa Vạn Vật",
    "landing.begin": "Gieo Quẻ",
    "landing.beginHint": "Tập trung vào câu hỏi, rồi bắt đầu gieo",

    "entry.placeholder": "Bạn đang băn khoăn điều gì?",
    "entry.submit": "Gieo Quẻ",
    "entry.suggest": "Nhờ AI gợi ý câu hỏi",
    "entry.thinking": "AI đang đọc câu hỏi…",

    "cast.first": "Gieo hào đầu tiên",
    "cast.line": "Gieo hào {n} trong 6",
    "cast.continue": "Xem Giải Quẻ",

    "reading.yourQuestion": "Câu hỏi của bạn",
    "reading.consulting": "Đang vấn quẻ…",
    "reading.error.422": "Quẻ này còn đang được hoàn thiện. Xin thử hỏi lại.",
    "reading.error.502": "Kết nối bị gián đoạn. Xin thử lại.",
    "reading.error.other": "Quẻ bị gián đoạn.",
    "reading.retry": "Vấn lại",
    "reading.askAnother": "Hỏi quẻ khác",
    "reading.upperTrigram": "Quái Trên",
    "reading.lowerTrigram": "Quái Dưới",
    "reading.image": "Tượng",
    "reading.cardJudgment": "Quẻ Từ",
    "reading.cardMeaning": "Ý Nghĩa",
    "reading.cardAdvice": "Lời Khuyên",
    "reading.expand": "Xem chi tiết 6 hào",
    "reading.collapse": "Thu gọn",
    "reading.advicePending": "Đang luận lời khuyên…",
    "reading.castAnother": "Gieo Quẻ Khác",
    "reading.home": "Về Trang Chủ",

    "clarify.placeholder": "Thêm đôi dòng bối cảnh…",
    "clarify.askAsIs": "Hỏi như vậy",
    "clarify.add": "Bổ sung bối cảnh",

    "lang.vi": "Tiếng Việt",
    "lang.zh": "中文",
    "lang.en": "English",
    "nav.exit": "Thoát",
  },
  zh: {
    "landing.subtitle": "周易",
    "landing.tagline1": "东方神秘经典",
    "landing.tagline2": "六十四卦 — 天地万物",
    "landing.begin": "起卦",
    "landing.beginHint": "凝神于你的问题，然后起卦",

    "entry.placeholder": "你心中所念为何？",
    "entry.submit": "占卜",
    "entry.suggest": "请 AI 完善问题",
    "entry.thinking": "AI 正在阅读你的问题…",

    "cast.first": "投掷第一爻",
    "cast.line": "投掷第 {n} 爻 / 6",
    "cast.continue": "查看解卦",

    "reading.yourQuestion": "你的问题",
    "reading.consulting": "正在请示神谕…",
    "reading.error.422": "此卦的解读尚在完善中，请再问一次。",
    "reading.error.502": "连接中断，请重试。",
    "reading.error.other": "解读被打断了。",
    "reading.retry": "重新解读",
    "reading.askAnother": "再问一卦",
    "reading.upperTrigram": "上卦",
    "reading.lowerTrigram": "下卦",
    "reading.image": "象",
    "reading.cardJudgment": "卦辞",
    "reading.cardMeaning": "卦义",
    "reading.cardAdvice": "建议",
    "reading.expand": "查看六爻详解",
    "reading.collapse": "收起",
    "reading.advicePending": "正在推演建议…",
    "reading.castAnother": "再起一卦",
    "reading.home": "返回首页",

    "clarify.placeholder": "补充一些背景…",
    "clarify.askAsIs": "就这样问",
    "clarify.add": "补充背景",

    "lang.vi": "Tiếng Việt",
    "lang.zh": "中文",
    "lang.en": "English",
    "nav.exit": "退出",
  },
  en: {
    "landing.subtitle": "BOOK OF CHANGES",
    "landing.tagline1": "The ancient Eastern oracle",
    "landing.tagline2": "64 Hexagrams — Heaven, Earth, All Things",
    "landing.begin": "Cast a Reading",
    "landing.beginHint": "Hold your question in mind, then begin",

    "entry.placeholder": "What's on your mind?",
    "entry.submit": "Divine",
    "entry.suggest": "Ask AI to refine",
    "entry.thinking": "AI is reading your question…",

    "cast.first": "Cast the first line",
    "cast.line": "Cast line {n} of 6",
    "cast.continue": "See the reading",

    "reading.yourQuestion": "Your question",
    "reading.consulting": "Consulting the oracle…",
    "reading.error.422": "The oracle is still learning about this question. Try asking again.",
    "reading.error.502": "The connection faltered. Please try again.",
    "reading.error.other": "The reading was interrupted.",
    "reading.retry": "Retry reading",
    "reading.askAnother": "Ask another",
    "reading.upperTrigram": "Upper Trigram",
    "reading.lowerTrigram": "Lower Trigram",
    "reading.image": "Image",
    "reading.cardJudgment": "The Judgment",
    "reading.cardMeaning": "Meaning",
    "reading.cardAdvice": "Guidance",
    "reading.expand": "Read the full interpretation",
    "reading.collapse": "Collapse",
    "reading.advicePending": "Drawing out the guidance…",
    "reading.castAnother": "Cast Again",
    "reading.home": "Home",

    "clarify.placeholder": "Add context…",
    "clarify.askAsIs": "Ask as is",
    "clarify.add": "Add context",

    "lang.vi": "Tiếng Việt",
    "lang.zh": "中文",
    "lang.en": "English",
    "nav.exit": "Exit",
  },
};

export const LOCALE_ORDER: Locale[] = ["vi", "zh", "en"];
export const DEFAULT_LOCALE: Locale = "vi";
